# Generated by Django 3.0.4 on 2020-03-24 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
                ('preco', models.FloatField(default=0.0)),
                ('dataDeCriacao', models.DateField(default=datetime.datetime(2020, 3, 23, 23, 8, 45, 28573))),
                ('estoque', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDeUsuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('primeiroNome', models.CharField(max_length=50)),
                ('ultimoNome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
            ],
        ),
    ]
