# Generated by Django 3.0.4 on 2020-03-24 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='dataDeCriacao',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 23, 9, 17, 24607)),
        ),
    ]
